CREATE TABLE IF NOT EXISTS Person (
id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT NOT NULL,
firstname TEXT NOT NULL,
status TEXT NULL,
email TEXT NULL,
login TEXT NULL,
password TEXT NULL,
linkedIn TEXT NULL,
cv TEXT NULL,
git TEXT NULL
);

CREATE TABLE IF NOT EXISTS Document (
id INTEGER PRIMARY KEY AUTOINCREMENT,
label TEXT NOT NULL,
format TEXT NULL,
date TEXT NULL,
importDate TEXT NULL,
downloadLink TEXT NULL,
teaching TEXT NULL
); 

CREATE TABLE IF NOT EXISTS Authorship (
userID,
docuID,
PRIMARY KEY (userID, docuID),
FOREIGN KEY (userID) REFERENCES Person(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (docuID) REFERENCES Document(id)
ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS Tag (
id INTEGER PRIMARY KEY AUTOINCREMENT,
label TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS HasTag (
tagID,
docuID,
PRIMARY KEY (tagID, docuID),
FOREIGN KEY (tagID) REFERENCES Tag(id)
ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (docuID) REFERENCES Document(id)
ON DELETE CASCADE ON UPDATE CASCADE
);