"""empty message

Revision ID: 5ff2c4112119
Revises: 
Create Date: 2019-03-28 14:00:24.672699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff2c4112119'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('document_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_title', sa.Text(), nullable=True),
    sa.Column('document_description', sa.Text(), nullable=True),
    sa.Column('document_format', sa.String(), nullable=True),
    sa.Column('document_date', sa.Text(), nullable=True),
    sa.Column('document_teaching', sa.String(), nullable=True),
    sa.Column('document_downloadLink', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('Person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_name', sa.String(length=25), nullable=True),
    sa.Column('person_firstName', sa.String(length=25), nullable=True),
    sa.Column('person_is_teacher', sa.Boolean(), nullable=True),
    sa.Column('person_email', sa.Text(), nullable=False),
    sa.Column('person_login', sa.Text(), nullable=False),
    sa.Column('person_password', sa.Text(), nullable=False),
    sa.Column('person_linkedIn', sa.Text(), nullable=True),
    sa.Column('person_cv', sa.Text(), nullable=True),
    sa.Column('person_git', sa.Text(), nullable=True),
    sa.Column('person_promotion', sa.Text(), nullable=True),
    sa.Column('person_is_admin', sa.Boolean(), nullable=True),
    sa.Column('person_last_seen', sa.Text(), nullable=True),
    sa.Column('person_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('person_git'),
    sa.UniqueConstraint('person_id'),
    sa.UniqueConstraint('person_linkedIn'),
    sa.UniqueConstraint('person_login'),
    sa.UniqueConstraint('person_password')
    )
    op.create_table('Tag',
    sa.Column('tag_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tag_id'),
    sa.UniqueConstraint('tag_id')
    )
    op.create_table('Authorship',
    sa.Column('authorship_person_id', sa.Integer(), nullable=False),
    sa.Column('authorship_document_id', sa.Integer(), nullable=False),
    sa.Column('authorship_date', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['authorship_document_id'], ['Document.document_id'], ),
    sa.ForeignKeyConstraint(['authorship_person_id'], ['Person.person_id'], ),
    sa.PrimaryKeyConstraint('authorship_person_id', 'authorship_document_id')
    )
    op.create_table('HasTag',
    sa.Column('hasTag_doc_id', sa.Integer(), nullable=False),
    sa.Column('hasTag_tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hasTag_doc_id'], ['Document.document_id'], ),
    sa.ForeignKeyConstraint(['hasTag_tag_id'], ['Tag.tag_id'], ),
    sa.PrimaryKeyConstraint('hasTag_doc_id', 'hasTag_tag_id')
    )
    op.create_table('IsFav',
    sa.Column('faved_docu_id', sa.Integer(), nullable=False),
    sa.Column('loving_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faved_docu_id'], ['Document.document_id'], ),
    sa.ForeignKeyConstraint(['loving_user_id'], ['Person.person_id'], ),
    sa.PrimaryKeyConstraint('faved_docu_id', 'loving_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('IsFav')
    op.drop_table('HasTag')
    op.drop_table('Authorship')
    op.drop_table('Tag')
    op.drop_table('Person')
    op.drop_table('Document')
    # ### end Alembic commands ###
